[package]
name = "Restaurant_API"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "1.3.3", features = ["test"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
time = "0.3.36"

[dependencies.models]
path = "./models"
