[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
poem = { version = "1.3.3", features = ["test"] }
rand = "0.9.0-alpha.2"
serde = { version = "1.0.215", features = ["derive"] }
